### PR TITLE
param refactoring

### PR DESCRIPTION
**Pull request by mcharleb**
Params are now stored in a large struct that can be accessed directly.

### CODE REVIEW

**Comment by mcharleb** [comment]
This is a minimal change to get param working without linker scripts. It is also set up so that if the linker script is run it will do no harm.

**Comment by mcharleb** [comment]
@LorenzMeier I think this change does what you were looking for.

**Comment by LorenzMeier** [comment]
Merged in upstream. Please continue on upstream cmake-2 branch

**Comment by mcharleb** [comment]
A python script generates a header defining all the parameters and then a C file initialized all the values. The struct contains the number of elements in the struct so the existing login can be used.

**Comment by mcharleb** [comment]
@LorenzMeier will do.

**Pull request merged**
