### PR TITLE
Work in progress adding QuRT support to cmake

### PR DESCRIPTION
**Pull request by mcharleb**
This is in no shape to merge. I just wanted to enable a dialog around the changes. I am trying to add QuRT support.

### CODE REVIEW

**Comment by mcharleb** [comment]
@modevico An attempt at the beginnings of QuRT support... comments welcome.

**Comment by jgoppert** [comment]
@mcharleb  Looks good! A couple of points to consider:
- I'd like to keep this all as vanilla cmake as possible so it is easy for new developers. I think this means separating the toolchain from the build flags. If you look at the toolchain files on your system/in the examples they are fairly sparse: http://www.cmake.org/cmake/help/v3.0/manual/cmake-toolchains.7.html and are not project specific. It would be great if a user wanted to switch to a different compiler that it took as little effort as possible, they just switch out their toolchain and then modify an existing set of build flags.
- This brings up the point of if we should have one massive file with if statements or separate files for build flags/ configs etc. An advantage for the massive file is that it highlights differences between the configuration, and it more difficult for a little used config to be invalidated when someone changes a common component. An advantage to the separate files is that it is easier to read.

**Comment by mcharleb** [comment]
@jgoppert I would much rather have it be as modular as possible. Huge files are simply not easy to understand and maintain. If there are shared components, they can be factored out into several shared modules.

I have moved the project specific data out of qurt-clang-hexagon.mk and into CMakeLists.txt.

**Comment by jgoppert** [comment]
- Yeah, I think that is a good idea to keep it modular.
- I think it is convention to put Toolchain in front of your toolchain file name.
- On looking at your last commit it seems you are moving all of the nuttx stuff out of the cmakelists.txt but you didn't put it in s a seperate nuttx config file yet, or did you just forget to add it to the commit?

**Comment by mcharleb** [comment]
I am approaching this in phases. Initially I want to get QuRT working, then posix, then NuttX. NuttX is the most complex and should be done in a way as to not complicate the other targets if possible.

**Comment by jgoppert** [comment]
@mcharleb  understandable

**Pull request closed without merging**
