### PR TITLE
Multi subscription for range finders

### PR DESCRIPTION
**Pull request by AndreasAntener**
**do not merge**

Hi @jgoppert 
I've been talking @mhkabir about lidar integration and wanted to give him a hand with this multi subscription thing. The change is more involving than I expected ;)

There are a few things to point out so I'm opening this PR for exactly that. And for Kabir to take over :)
- First, the main change that was needed to get multiple distance sensors publishing at the same time is in their drivers. Until now only the first recognized range finder advertised itself. I also updated the various priority settings according to what I know about the sensors reliability.
- To be able to choose the range finder based on it's priority it needs "lazy subscriptions" (flow and lidar drivers are started after the estimator). I modified the subscription wrappers to check on subscription existence before they give updates and ready priority.
- The estimator now only uses the distance sensor with the highest priority.

I'm not sure if the last item is correct or wanted. IMHO if I have the flow and a lidar attached I only want to use the distance reading from the lidar. But I guess there are other use-cases where it's different.

What do you think?

**NOTE**: I have only bench tested this to verify that it recognizes multiple distance sensors. Otherwise this is not tested.

Furthermore, I did not yet update EKF. That will of course be easy once this looks good. The priority handling that I put in there could be generalized and used in both estimators afterwards. In case your wondering, I believe this is independent from https://github.com/PX4/Firmware/pull/2818 as the sensor voting and priority handling for gyro/accel/baro is quite specific to those types of sensors.

### CODE REVIEW

**Comment by mhkabir** [comment]
Hey Ada, 
Looks great, I reviewed the code. I'll pull this into my working branch and add the things I told you about. Any suggestions from James are highly appreciated.
The lidar outperforms sonar in _all_ conditions, so I think point (3) is just fine. (1) and (2) are great!

Just a self-note, I plan to adding (in stages):
- As in PX4#2818, multi-accel/gyro fallbacks to LPE.
- Ground/terrain estimate as separate filter state
- Use terrain estimate for flow scaling, instead of Z estimate
- Add support for correction for translation/rotation between sensors. A general sensor calibration system can generate this. e.g I use KALIBR https://github.com/ethz-asl/kalibr
- Fix / check flow body rotation correction. (TODO : Use flow gyro [drifts, but tightly synced] or PX4 gyro [no drift but loose sync])
- General visual tag position fusion.

**Comment by jgoppert** [comment]
@AndreasAntener, @mhkabir  Thanks for your help! This looks good to me. I'd like to get this tested before I pull as this branch has a lot of flight time on it. Do you think you will have an opportunity to fly this soon?
- I think that only using the distance sensor with highest priority is fine.
- I think fallback to a lower priority distance sensor if an error is detected should work out of the box with your code, but it would be worth checking that we have that functionality.
- It is unfortunate that we have to allocate the max number of uorb multi subscriptions for the distance sensor and then spend the time to check each one. I can't think of any better way to do this though with the current api. Is this what is done for the gyros/accels etc? It would be nice if subscriptions returned a vector that you could cycle through instead of just one instance. That way we wouldn't have to repeat the same chunk of code everywhere.

**Comment by AndreasAntener** [comment]
About test flying on my end: I'm pretty limited in time atm, but yes I'd like to give your estimator a try asap, heard good things about it and I like the code :) 

The fallback wouldn't work right now because I'm not going lower in priorities anymore. That would be easily fixed I think, but: does the fault detection know if the sensor is faulty? What's the difference between a fault and it being out of range? Does this even matter?

The way it works for the other sensors is that you get an array for each sensor type and you just iterate through them. `sensors_combined` gives you that, so you just subscribe to one topic. In #2818 Lorenz also added a data validator class that you can feed with sensor data including priorities which then outputs the value you want to use. It's something you should have a look at anyway, he already added this fault detection/failover for EKF and Q in his PR (see last 3 commits, I wasn't brave enough yet to merge and update LPE with it ;)). The data validator isn't really suited for range finder data though. But maybe it would make sense to do something similar for distance sensors.

**Comment by AndreasAntener** [comment]
Thinking a little more about #2818, specifically this: https://github.com/PX4/Firmware/commit/ad2058427dfd2c3d4886ce0bed55dee6d247f90e#diff-b2cdb687c37812923ec65dc8fc767506R2090

If we'd add distance sensors to the sensors app as well it would make my lazy subscription code obsolete. All that's left then would be to adapt the data validator so we could use it for distance sensors too. Maybe the fault detection you're doing in LPE is general enough to extract it and put it there?

**Comment by AndreasAntener** [comment]
Sorry for the monologue here ;) but Lorenz just advised against putting anything new into the sensors app because the plan is to get rid of it eventually.

So instead, James subscription wrapper could the same thing:
- check for new publishers as long as the vehicle is not armed
- return an array with values and priorities

**Comment by jgoppert** [comment]
@AndreasAntener I like the idea of putting an array in the subscription wrappers. We should see how this ties into the work that @thomasgubler has done with multiple platform pub/sub. I think he has crated a new api that I wanted to update LPE to at some point, but maybe those ideas can be applied to his code there.

I think the fault detection that LPE implements is too taxing for use everywhere. It monitors the measurement standard deviation vs. expected and throws a flag when the standard deviation is too high. This requires an inverse. I think it is practical for the position loop because it is running at a lower rate and fairly small measurement dimensions, gps is the largest with 6. It is more than just simple out of measurement range and can be used to detect a degrading sensor, or one with lower quality than expected. This is important for my work where the vehicle will be expected to operate without significant maintenance for long periods.

**Comment by mhkabir** [comment]
I'd like to base off this as soon as possible, and then we can modify the wrapper in order to do the subscriptions, sensor fallback, etc. Fault detection or data validation for a rangefinder would be tricky to generalise, I think. Being able to fly with flow is something I need soon. 
What I propose is that we drop the prio based validation/switching/fallback (just for now) and just get in the auto-selection of lidar / sonar which would get this working as required for a number of testers. Also, it would reduce the logic Andreas has added, while still keeping lazy subscription. 
What do you think @AndreasAntener @jgoppert?

**Pull request closed without merging**
