### PR TITLE
Cmake 2

### PR DESCRIPTION
**Pull request by jgoppert**
This is the second attempt at cmake build support. It is a work in progress.

### CODE REVIEW

**Comment by jgoppert** [comment]
@mcharleb I agree that it would be nice to have OS hooks like you had setup before to eliminate if statements in the main CMakeLists.txt file. That is something that I can adjust easily, as most of the macros are already named to support the calling based on OS name that you had setup previously. I'll work on that now.

**Comment by jgoppert** [comment]
Someone did some auto-formatting on master, which made this really painful to rebase. So just finished that, so it is easier for us to look at.

**Comment by mcharleb** [comment]
@jgoppert I synced from cmake-2 and build px4fmu-v2_simple, posix-sitl_simple and qurt-hil_simple. The last two appear to be stubs for now. 

How can I best co-ordinate with you and not do things you are working on? I will focus on the qurt build for now until I have it working. Then I can help with the posix build.

**Comment by mcharleb** [comment]
@jgoppert I'll convert the macros to functions in cmake/qurt/px4_target_impl.cmake

**Comment by jgoppert** [comment]
@mcharleb great, thanks! I added the os abstraction that you wanted for flags and pre_build targets. It should be straight forward to extend, I put plenty of comments everywhere. I still haven't abstracted the executable/ firmware creation. Let me know if you think this is needed. My trying to determine how closely the firmware build is tied to OS vs. board etc and if it would be worth it, or if it is more similar to modules where we have OS dependent sources.

**Comment by mcharleb** [comment]
@jgoppert Rather than 

```
add_subdirectory(src)
```

Wouldn't it be cleaner to:

```
add_subdirectory(cmake/${OS})
```

or

```
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake/${OS})
include(px4_os_utils)
```

?

The name cmake/px4_${OS}_utils.cmake isn't really accurate as its an implementation of a required interface. Perhaps px4_${OS}_funcs.cmake or  px4_${OS}_impl.cmake?

The CMakeLists.txt in src will have huge amounts of "if {OS}" code otherwise.

**Comment by mcharleb** [comment]
@jgoppert I don't see what I would do for px4_qurt_add_firmware() because the qurt build is done when it creates the exe.

**Comment by jgoppert** [comment]
@mcharleb The cmake directory is just for functions, it doesn't make sense to put CMakeLists.txt there, so I don't think add_subdirectory(cmake/${OS}) is the right way to go. 

I like  px4${OS}_impl.cmake, I will rename it.

The current module.mk and generated module CMakeLists.txt files have (if {OS}== ... ) for sources and dependencies etc, but I do agree that the executable is more complicated than the modules with more subtargets, and probably warrants some abstraction. I think once you add your posix/ qurt implementations, it will be more clear which is readable.

**Comment by jgoppert** [comment]
@mcharleb So we could have it create an empty target that just touches a stamp or something, or we could create an if OS in the main file, whichever you think is best.

**Comment by jgoppert** [comment]
@mcharleb  We could also create a px4_add_executable, and if it is nuttx, this could create the firmware target as well.

**Comment by jgoppert** [comment]
I renamed the modules, I also allowed for us to add even more specific implementations if we want:

``` cmake
if (EXISTS px4_impl_${OS}_${BOARD})
    include(px4_impl_${OS}_${BOARD})
else()
    include(px4_impl_${OS})
endif(
```

**Comment by mcharleb** [comment]
@jgoppert I am having some issues with the meta-language you have created on top of cmake. If I am trying to append to an empty list using a function I get a very confusing error:

```
function(px4_qurt_add_modules)
        px4_parse_function_args(
                        NAME px4_qurt_add_modules
                        MULTI_VALUE MODULE_LIST 
                        ONE_VALUE BOARD
                        REQUIRED MODULE_LIST BOARD
                        ARGN ${ARGN})
        include(config-qurt-${BOARD})
        set(config_module)
        px4_set_config_modules(config_modules)
        list(APPEND ${MODULE_LIST} ${config_modules})
endfunction()
...
set(module_list)
px4_qurt_add_modules(MODULE_LIST ${module_list} BOARD ${BOARD})
```

CMake Error at cmake/px4_base.cmake:106 (message):
  px4_qurt_add_modules requires argument MODULE_LIST, ARGN:
  MODULE_LIST;BOARD;hil
Call Stack (most recent call first):
  cmake/px4_impl_qurt.cmake:253 (px4_parse_function_args)
  src/CMakeLists.txt:75 (px4_qurt_add_modules)

Since ${module_list} is empty it chokes on the missing value. I'm not sure what I am supposed to do to pass in a variable (possibly empty list) and have it append to the list. I like the idea behind your px4_parse_function_args but it adds a significant overhead to debugging and figuring out how to get the syntax just right.

**Comment by jgoppert** [comment]
@mcharleb 

Sorry, I didn't see this earlier, one option is:

``` cmake
if(module_list)
   px4_qurt_add_modules(MODULE_LIST ${module_list} BOARD ${BOARD})
endif()
```

Another is, removing module_list from the required arguments, and catching the empty list inside your function and handling it:

``` cmake
 function(px4_qurt_add_modules)
                        NAME px4_qurt_add_modules
                        MULTI_VALUE MODULE_LIST 
                        ONE_VALUE BOARD
                        REQUIRED  BOARD
                        ARGN ${ARGN})
if(MODULE_LIST)
endif()
endfucntion()
```

px4_parse_function_args is  close to standard cmake but it simplifies your life a bit, see (http://www.cmake.org/cmake/help/v3.0/module/CMakeParseArguments.html)

CMakeParseArguments is the standard way to pass key value pairs to functions, which is  helpful when reading the code since we have a lot of custom modules to support our abstraction layer.

px4_parse_function_args does everything CMakeParseArguments does, but it makes it clearer what CMakeParseArguments is doing and it also provides the optional required list, which helps to throw more meaningful errors.

**Comment by jgoppert** [comment]
@mcharleb , @LorenzMeier The romfs is now built and linked to the executable for nuttx. I'm still debugging why it isn't starting up normally. I'm happy with the structure at this point, so I think we can focus on fleshing this out.

The nuttx usb terminal might not be starting do to one of the other drivers not being enabled and causing an error in the boot script. I'll hook up an ftdi and debug later, unless you guys have time.

**Comment by jgoppert** [comment]
@mcharleb  Lorenz asked me to create a pull request against master, so let's continue discussion there: https://github.com/PX4/Firmware/pull/2821

**Pull request closed without merging**
