### PR TITLE
Added support for multiple config files per OS

### PR DESCRIPTION
**Pull request by mcharleb**
New build configs are in:

cmake/${OS}/${OS}-${BOARD}-${TARGET_LABEL}

i.e. posix-sitl-simple

Signed-off-by: Mark Charlebois charlebm@gmail.com

### CODE REVIEW

**Comment by mcharleb** [comment]
@jgoppert I tried rebasing on your new cmake branch, but it still shows a merge conflict

**Comment by jgoppert** [comment]
@mcharleb Merged.

**Comment by jgoppert** [comment]
I'm resolving some build errors now on this merge.

**Comment by mcharleb** [comment]
There are lots of missing CMakeList.txt files. Which ones can I help to add?

**Comment by jgoppert** [comment]
@mcharleb  What are you most familiar with? Want to focus on just posix or qurt, just pick one and I'll stay out of your way.

**Comment by mcharleb** [comment]
I can do the posix and qurt ones if you can do the nuttx ones

**Comment by jgoppert** [comment]
@mcharleb That works for me. I'll try to do ros next, when I finish nuttx.

**Pull request merged**
