### PR TITLE
added accelerometer bias estimation

### PR DESCRIPTION
**Pull request by RomanBapst**
Enable accelerometer bias estimation.

### CODE REVIEW

**Comment by RomanBapst** [comment]
@jgoppert I enabled accel bias estimation because the estimated velocity and position in my first outdoor flight was not really smooth. Looking at the log, it seems like there is a mismatch between prediction and measurement. I assume that adding a bias for the accelerometer will improve things much.

**Comment by RomanBapst** [comment]
This is the first flight I did:
http://logs.uaventure.com/view/xiGzDWjuaYmEdcr4aGboqU

**Comment by jgoppert** [comment]
@tumbili @mhkabir
Merged this by hand, is in cart_pos_estimator branch now. Caused the stack size to go up by about 1.5 kB due to increased size of Q, P, x. We need to evaluate if it really helps or not. We can due this by setting the bias random walk process noise to zero before flight. PN_B. I currently have it set to 0.01.

Here is a flight log:
https://github.com/jgoppert/lpe-analysis/blob/master/15-10-01%20jgoppert%20accel%20bias.ipynb

**Comment by RomanBapst** [comment]
@jgoppert Hi James, I'm currently at IROS and haven't had any time to further work on this.
I'm back on Tuesday and would have time to continue with it. I also had interesting talks with Paul Riseborough about the estimator. I think we should arrange a talk then. What do you think?

**Comment by jgoppert** [comment]
Sounds good.

**Pull request closed without merging**
