### PR TITLE
lpe: redone vision velocity derivation

### PR DESCRIPTION
**Pull request by TSC21**

### CODE REVIEW

**Comment by TSC21** [comment]
James I am having a problem with your suggestion: `math::matrix` requires constant template arguments if the values of the arguments are not constants it does not compile so right now it is not being feasible. Do you have other suggestion?

The thing about multiplying by a high value factor is legit but it's hacky and I don't "like" it. Probably there's better programming solution to surpass that constant value requirement but can't see how to without almost repeting all the method code for both vel/no-vel measurements.

**Comment by jgoppert** [comment]
Maybe the best approach is just to make the vision velocity a separate correction function.

**Comment by TSC21** [comment]
@jgoppert I think is done. Please check

**Comment by mhkabir** [comment]
Does this PR handle the derivate vision position as a velocity reading?

**Comment by TSC21** [comment]
@mhkabir the kalman filter already does that, so yes it handles.

**Pull request merged**
