### PR TITLE
LPE : Improve dynamic estimation

### PR DESCRIPTION
**Pull request by mhkabir**
Don't merge yet.
Major refactoring to the sonar handling and dynamic estimation.

### CODE REVIEW

**Comment by mhkabir** [comment]
I still need to think about how to go about data re-validation. Currently, in flight if the flow/vision/vicon is totally lost (and doesn't come back) , it will keep integrating accelerometers till the estimate inflates out of bounds.

Some good ideas here : https://github.com/PX4/Firmware/pull/2060

**Comment by mhkabir** [comment]
@jgoppert So I've separated the sonar from the flow, and I need your help in getting the multi-sub working. Currently I coded it to check for the type of ranger to choose sonar/lidar, but this obviously isn't working without the proper subscription. 
Can you please help/have a look ? :)

**Comment by jgoppert** [comment]
Out of town today.

**Comment by jgoppert** [comment]
Just have a look at my uorb/subscription.cpp class.  there is probably something I missed

**Comment by mhkabir** [comment]
@jgoppert Unfortunately can't figure out if anything is wrong. I'll wait for you. 
The subscription is only getting the sonar data and not the Lidar. Lidar is probably getting second place since it's driver is started later. I think that you don't have issues since you're only running Lidar, and not flow.

**Comment by mhkabir** [comment]
We need to think about using the 3D fix availability for GPS position estimation.

**Comment by mhkabir** [comment]
@jgoppert Can you please review my changes? I'll try merging head again to see if the subscription works. 
The only thing left is to use another metric to detect the total loss of flow / GPS. Even with my changes,  if say flow is lost permanantly,  the fault detection won't trigger and the estimator continues estimation with no data. 
I added a check to constrain integration of accel (dead reckoning)  to  a maximum of 2 seconds after all position sources are lost. It's just detection of "lost" that needs to be done properly. 
These changes should handle many corner cases and make the system more robust and easier to test for others.

**Comment by jgoppert** [comment]
The changes look good to me. I haven't tested yet, but will  maybe tomorrow. I think if flow hasn't been received for a timeout period, just set flow initialized to false. I think that should handle it correctly.

**Comment by mhkabir** [comment]
@jgoppert I don't exactly mean timeout when I say loss for flow/GPS.
For flow :
If the copter is below/over a certain altitude, there is no _valid_ data at all, even though information its coming in (hence not a timeout) This is what we need to detect and set a fault flag for.
For GPS:
If we don't have a 3D fix or lose fix in flight (again, not a timeout), this needs to be detected and a fault flag set. 
The estimator keeps estimating in both the above examples, which will lead to state divergence and a crash.

I'm still thinking about how to implement this satisfactorily ;)

**Comment by jgoppert** [comment]
Maybe we could measure the time since a "good" measurement. And if it has
been too long, then deinitialize the sensor.

**Comment by mhkabir** [comment]
@jgoppert Yup, sounds good. That's what I wanted to do. Only thing is, how to define "good" ? 
Deinit should be OK, but just letting it remain in "fault" state shouldn't be bad either?

The canEstimateXY currently checks for a fault + init on flow/GPS and fault + init + timeout on vicon/vision.

**Comment by jgoppert** [comment]
I think for GPS, 3d fix with eph/ epv under a threshold defined by a parameter.
I think for lidar, within min/max range, this would effectively turn off lidar estimation when we climb out of range as well which would be good.

**Comment by mhkabir** [comment]
Then for flow, we can do a zero check on the pixel flow ( e.g lens cap closed )  and a altitude check ( within 32 cm and some upper bound determined by tests )

**Pull request merged**
